In [1]:
import pandas as pd

In [50]:
events_df = pd.read_csv("events.csv")
ginf_df = pd.read_csv("ginf.csv")

In [3]:
ginf_df.head()

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n
0,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,1,1.56,4.41,7.42,NaN,NaN,NaN,NaN
1,Aw5DflLH/,/soccer/germany/bundesliga-2011-2012/augsburg-...,True,2011-08-06,D1,2012,germany,FC Augsburg,SC Freiburg,2,2,2.36,3.60,3.40,NaN,NaN,NaN,NaN
2,bkjpaC6n/,/soccer/germany/bundesliga-2011-2012/werder-br...,True,2011-08-06,D1,2012,germany,Werder Bremen,Kaiserslautern,2,0,1.83,4.20,4.80,NaN,NaN,NaN,NaN
3,CzPV312a/,/soccer/france/ligue-1-2011-2012/paris-sg-lori...,True,2011-08-06,F1,2012,france,Paris Saint-Germain,Lorient,0,1,1.55,4.50,9.40,NaN,NaN,NaN,NaN
4,GUOdmtII/,/soccer/france/ligue-1-2011-2012/caen-valencie...,True,2011-08-06,F1,2012,france,Caen,Valenciennes,1,0,2.50,3.40,3.45,NaN,NaN,NaN,NaN

In [4]:
premier_matches = ginf_df[(ginf_df["season"] == 2016) & (ginf_df["league"] == "E0")].reset_index(drop=True)

In [5]:
events_df.head()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0

In [6]:
goal_events = events_df[events_df["is_goal"] == 1]

In [7]:
goals_at_premier = pd.merge(premier_matches, goal_events, left_on="id_odsp", right_on="id_odsp", how="left")

In [8]:
goals_at_premier.head()

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,bRrgEJw3/,/soccer/england/premier-league-2015-2016/bourn...,True,2015-08-08,E0,2016,england,Bournemouth,Aston Villa,0,...,NaN,NaN,5.0,1.0,1.0,3.0,3.0,2.0,3.0,0.0
1,CjbbBHNL/,/soccer/england/premier-league-2015-2016/evert...,True,2015-08-08,E0,2016,england,Everton,Watford,2,...,NaN,NaN,12.0,1.0,1.0,3.0,1.0,0.0,1.0,0.0
2,CjbbBHNL/,/soccer/england/premier-league-2015-2016/evert...,True,2015-08-08,E0,2016,england,Everton,Watford,2,...,NaN,NaN,13.0,1.0,1.0,15.0,1.0,1.0,1.0,0.0
3,CjbbBHNL/,/soccer/england/premier-league-2015-2016/evert...,True,2015-08-08,E0,2016,england,Everton,Watford,2,...,NaN,NaN,4.0,1.0,1.0,3.0,1.0,1.0,1.0,0.0
4,CjbbBHNL/,/soccer/england/premier-league-2015-2016/evert...,True,2015-08-08,E0,2016,england,Everton,Watford,2,...,NaN,NaN,3.0,1.0,1.0,3.0,1.0,1.0,1.0,0.0

In [9]:
goals_at_premier.columns

Index(['id_odsp', 'link_odsp', 'adv_stats', 'date', 'league', 'season',
       'country', 'ht', 'at', 'fthg', 'ftag', 'odd_h', 'odd_d', 'odd_a',
       'odd_over', 'odd_under', 'odd_bts', 'odd_bts_n', 'id_event',
       'sort_order', 'time', 'text', 'event_type', 'event_type2', 'side',
       'event_team', 'opponent', 'player', 'player2', 'player_in',
       'player_out', 'shot_place', 'shot_outcome', 'is_goal', 'location',
       'bodypart', 'assist_method', 'situation', 'fast_break'],
      dtype='object')

In [10]:
columns = ["id_odsp", "date", "ht", "at", "id_event", "sort_order", "time", "text", "side", "event_team", "opponent", "player"]
goals_at_premier = goals_at_premier[columns]

In [11]:
goals_at_premier["event_type"] = "goal"

In [30]:
def add_match_start_end_and_event(grouped_df):
    df = grouped_df.copy()
    if df.shape[0] == 1 and pd.isna(df["id_event"].iloc[0]):
        row_as_dict = df.iloc[0].to_dict()
        df_data = [
            {
                **row_as_dict,
                "id_event": f'{row_as_dict.get("id_odsp", "bozuk/")[:-1]}0',
                "sort_order": 0,
                "time": 0,
                "event_type": "start"
            },
            {
                **row_as_dict,
                "id_event": f'{row_as_dict.get("id_odsp", "bozuk/")[:-1]}1',
                "sort_order": 1,
                "time": 90,
                "event_type": "finish"
            },
        ]
        df = pd.DataFrame(df_data)
        return df
    else:
        last_event = df["sort_order"].max()
        last_time = max(df["time"].max(), 90)

        first_row = df.iloc[0]

        match_start = first_row.copy()
        match_start["time"] = 0
        match_start["sort_order"] = 0
        match_start["event_type"] = "start"

        match_last = first_row.copy()
        match_last["time"] = last_time
        match_last["sort_order"] = last_event + 2
        match_last["event_type"] = "finish"

        df["sort_order"] = df["sort_order"].apply(lambda row: int(row + 1))
        df["id_event"] = df.apply(lambda row: row.get("id_odsp", "bozuk/")[:-1] + str(row["sort_order"]), axis=1)

        df.loc[-1] = match_last
        df.index = df.index + 1
        df.sort_index(inplace=True) 
        
        df.loc[-1] = match_start
        df.index = df.index + 1
        df = df.sort_values("sort_order").reset_index(drop=True)
        
        return df

goals_at_premier = goals_at_premier.groupby("id_odsp").apply(add_match_start_end_and_event).reset_index(drop=True)

In [40]:
goals_at_premier["id_event"] = goals_at_premier.apply(lambda row: row.get("id_odsp")[:-1] + str(int(row["sort_order"])), axis=1)

In [47]:
goals_at_premier = goals_at_premier["side"].fillna(-1)

In [49]:
goals_at_premier

0      -1.0
1      -1.0
2       2.0
3       2.0
4       1.0
       ...
1786    2.0
1787    1.0
1788    2.0
1789    2.0
1790    2.0
Name: side, Length: 1791, dtype: float64

In [48]:
int_columns = ["sort_order", "time", "side"]
for col in int_columns:
    goals_at_premier[col] = goals_at_premier[col].apply(int)

KeyError: 'sort_order'

In [33]:
goals_at_premier

,id_odsp,date,ht,at,id_event,sort_order,time,text,side,event_team,opponent,player,event_type
0,bRrgEJw3/,2015-08-08,Bournemouth,Aston Villa,bRrgEJw365,65.0,72.0,"Goal! Goal! Bournemouth 0, Aston Villa...",2.0,Aston Villa,Bournemouth,rudy gestede,goal
1,CjbbBHNL/,2015-08-08,Everton,Watford,CjbbBHNL11,11.0,13.0,"Goal! Goal! Everton 0, Watford 1. Migu...",2.0,Watford,Everton,miguel layun,goal
2,CjbbBHNL/,2015-08-08,Everton,Watford,CjbbBHNL63,63.0,75.0,"Goal! Goal! Everton 1, Watford 1. Ross...",1.0,Everton,Watford,ross barkley,goal
3,CjbbBHNL/,2015-08-08,Everton,Watford,CjbbBHNL72,72.0,83.0,"Goal! Goal! Everton 1, Watford 2. Odio...",2.0,Watford,Everton,odion ighalo,goal
4,CjbbBHNL/,2015-08-08,Everton,Watford,CjbbBHNL76,76.0,86.0,"Goal! Goal! Everton 2, Watford 2. Arou...",1.0,Everton,Watford,arouna kone,goal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,xYXMWvIM/,2016-05-15,Newcastle,Tottenham,xYXMWvIM78,78.0,87.0,"Goal! Newcastle United 5, Tottenham Hotspur 1...",1.0,Newcastle,Tottenham,daryl janmaat,goal
1060,bsZIXK2G/,2016-05-17,Manchester Utd,Bournemouth,bsZIXK2G30,30.0,45.0,"Goal! Manchester United 1, Bournemouth 0. Way...",1.0,Manchester Utd,Bournemouth,wayne rooney,goal
1061,bsZIXK2G/,2016-05-17,Manchester Utd,Bournemouth,bsZIXK2G56,56.0,75.0,"Goal! Manchester United 2, Bournemouth 0. Mar...",1.0,Manchester Utd,Bournemouth,marcus rashford,goal
1062,bsZIXK2G/,2016-05-17,Manchester Utd,Bournemouth,bsZIXK2G67,67.0,88.0,"Goal! Manchester United 3, Bournemouth 0. Ash...",1.0,Manchester Utd,Bournemouth,ashley young,goal
1063,bsZIXK2G/,2016-05-17,Manchester Utd,Bournemouth,bsZIXK2G69,69.0,90.0,"Own Goal by Chris Smalling, Manchester United....",2.0,Bournemouth,Manchester Utd,chris smalling,goal